### ISSUE TITLE
Performance lower than paper

### ISSUE THREAD

**Issue by moliq1** [Marcovaldong/ISGAN#1]
Hi, Very thanks for the code. I run it on LFW dataset, the train/valid is randomly generated(since not include in the original repo), all parameters are almost the same, what I got is 
![ssim_result](https://user-images.githubusercontent.com/18486307/54654137-300cc980-4af8-11e9-9bfa-1bc8e6dc7bf3.jpg)
![psnr_result](https://user-images.githubusercontent.com/18486307/54655380-b75c3c00-4afc-11e9-87dd-9d2bee5687a1.jpg)
The best Cover SSIM I got is 0.92, Secret SSIM is 0.90, PSNR all bellow 30.  which is lower than the paper. So, is there anything else I missed ?

**Comment by StoveJunJun** [comment]
> Hi, Very thanks for the code. I run it on LFW dataset, the train/valid is randomly generated(since not include in the original repo), all parameters are almost the same, what I got is
> ![ssim_result](https://user-images.githubusercontent.com/18486307/54654137-300cc980-4af8-11e9-9bfa-1bc8e6dc7bf3.jpg)
> ![psnr_result](https://user-images.githubusercontent.com/18486307/54655380-b75c3c00-4afc-11e9-87dd-9d2bee5687a1.jpg)
> The best Cover SSIM I got is 0.92, Secret SSIM is 0.90, PSNR all bellow 30. which is lower than the paper. So, is there anything else I missed ?

Hi,I ran it in the VOC dataset,But I got a worse result than you,.I was wondering if you could share the code you run to me ?I don't know  what happened so I want to make  a comparison,Thanks

**Comment by AldrinAJ** [comment]
I'm having results that are not promising while evaluation, especially during model.eval().. could you please elaborate the things you did..?!

**Comment by StoveJunJun** [comment]
> I'm having results that are not promising while evaluation, especially during model.eval().. could you please elaborate the things you did..?!

Hey,What  performace did you get?What's SSIM and the MSSIM  you got?

**Comment by Marcovaldong** [comment]
@AldrinAJ Sorry, the code of this repo is almost the first branch, I forgot to update it before I got away from school. I'll try to update it when I'm not busy.

**Comment by AldrinAJ** [comment]
That's alright, Thanks ..

**Comment by HarryAB** [comment]
where is the kv.npy

**Comment by Marcovaldong** [comment]
> where is the kv.npy

You can create one by yourself.
