### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by StoveJunJun** [Marcovaldong/ISGAN#2]
Namespace(batch_size=4, beginpoint=0, beta1=0.5, beta2=0.999, crop_size=0, decay_epoch=15, fliplr=False, input_size=256, lambdaA=0.5, lambdaB=0.85, lambdaC=0.3, log_schedule=20, lr=0.0001, num_epochs=10, resize_scale=256, use_cuda=True, weight_decay=0.005)
Total number of parameters: 407481
Total number of parameters: 185857
Total number of parameters: 357066
Total number of parameters: 98268
.\train.py:80: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(m.weight)
I:\Python3.6\lib\site-packages\torchvision\transforms\transforms.py:188: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Starting to train the model...
current learning rate: 0.000100 weight decay: 0.005000
.\train.py:216: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  avg_loss.append(loss.data[0])
.\train.py:231: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  epoch, params.num_epochs, idx*params.batch_size, len(train_data_loader.dataset), loss.data[0],
.\train.py:233: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  encoder_ssim.data[0], encoder_mssim.data[0], encoder_mse.data[0],
.\train.py:234: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  decoder_ssim.data[0], decoder_mssim.data[0], decoder_mse.data[0], disloss1.data[0]))
Epoch [1/10]  Step [80/6067]  Loss 2.4371 encoder_ssim 0.0690 enocder_mssim 0.0690 encoder_mse 0.7814  decoder_ssim 0.3675 decoder_mssim 0.3675 decoder_mse 0.0328 disloss 0.7258
Traceback (most recent call last):
  File ".\train.py", line 608, in <module>
    total_train(beginpoint=params.beginpoint)
  File ".\train.py", line 441, in total_train
    train(epoch)
  File ".\train.py", line 208, in train
    encoder_mssim = MSSIM_loss(stego, target)
  File "I:\Python3.6\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "H:\LuJunJun\ISGAN-master\src\pytorch_mssim.py", line 135, in forward
    return msssim(img1, img2, window_size=self.window_size, size_average=self.size_average)
  File "H:\LuJunJun\ISGAN-master\src\pytorch_mssim.py", line 103, in msssim
    img1.__class__.__name__)
**RuntimeError: Input images must be Variables, not Tensor**

**Comment by Marcovaldong** [comment]
You can debug it by yourself.

**Comment by zhengziqiang** [comment]
@Marcovaldong You are really really really a bad developer!
